spring:
  datasource:
    generate-unique-name: false
  h2:
    console:
      enable: true
      path: /h2-console
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
